### ISSUE TITLE
Has this project been dropped?

### ISSUE THREAD

**Issue by itsN1X** [VIT-OCW/VIT-OCW.github.io#3]
Looking out for Open Courseware, VIT.
Is this org dead?
And did you get any permissions for this OCW, for this is Open? And VIT doesn't explicitly support that though..

**Comment by karthikb351** [comment]
The few of us who started this aren't in college anymore. Happy to pass this on to someone from college who can actively maintain this.

**Comment by itsN1X** [comment]
I'll contribute..
It'd great, if I'm added.

**Comment by karthikb351** [comment]
Feel free to send a PR for the relevant repo.

**Comment by itsN1X** [comment]
(: Awesome

**Comment by itsN1X** [comment]
Would it be better to add me to this org, or shall I set up a new OCW org?
tysm (:

**Comment by itsN1X** [comment]
Closing issues.
$I'll get back ] ] wen richer.

Feel free to refer @14bme0133.
